theme: "hugo-PaperMod"
baseURL: https://amirography.com/
languageCode: en-us
title: Nececssitated
author: "Amir Alesheikh"

params:
    env: production
    homeInfoParams: 
        enabled: true
        Title: By Amir Alesheikh
        Content: facination about how humans interact and get affected with their environments
    socialIcons:
      - name: "twitter"
        url: "https://twitter.com/amirography"
      - name: "linkedin"
        url: "https://www.linkedin.com/in/amirography/"
      - name: "telegram"
        url: "https://telegram.me/amirography"
      - name: "github"
        url: "https://github.com/amirography"
    ShowBreadCrumbs: true
    ShowPostNavLinks: true
    ShowCodeCopyButtons: true
    
menu:
    main:
      - identifier: categories
        name: categories
        url: /categories/
        weight: 10
      - identifier: tags
        name: tags
        url: /tags/
        weight: 20
markup:
    goldmark:
        renderer:
          unsafe: true
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]
